### PR TITLE
Setup Math Magicians React app

### PR DESCRIPTION
**Pull request by yaredtekle022**
### **This list of activities was made** 

> Set up the environment and tools needed to develop a React application

> Set linters

> Used Gitflow

>Documented my work in a professional way

### CODE REVIEW

**Review by TedLivist — COMMENTED** [review]
## STATUS: INVALID CODE REVIEW REQUEST 🛑 🛑

Hi @yaredtekle022,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### You have two accounts working on the project, @yaredtekle022 and @yaredtt, kindly redo this project using only the account registered with Microverse.

### Kindly fix your linter errors and remove this part of your README.

image

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by julie-ify — COMMENTED** [review]
Hi @yaredtekle022,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### Kindly redo the project and ensure ONLY the github account registered with Microverse makes commits as requested by the previous reviewer.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by yaredtekle022** [comment]
### **Hello @julie-ify** 
Thanks for your suggestion  👍 
To make sure I only push with the Microverse GitHub account, but since these two accounts are registered with the same email I can't remove contributions for the other email

**Comment by yaredtekle022** [comment]
### Thanks **@mukhammadrizooff** 

I will implement this on later projects.

**Pull request merged**
